phpfpm:
    command: 'php-fpm --allow-to-run-as-root'
    image: 'mglaman/docker-php-bcmath:7.0-fpm'
    volumes: ['./conf/fpm.conf:/usr/local/etc/php-fpm.conf', './:/var/platform:cached', './conf/php.ini:/usr/local/etc/php/conf.d/local.ini']
    links: [mariadb]
    environment: { PLATFORM_DOCKER: glamanate, PHP_IDE_CONFIG: serverName=glamanate.platform }
mariadb:
    command: 'mysqld --verbose'
    image: mariadb
    ports: ['3306']
    volumes: ['./conf/mysql.cnf:/etc/mysql/my.cnf', './db-seed:/docker-entrypoint-initdb.d/']
    environment: { MYSQL_DATABASE: data, MYSQL_USER: mysql, MYSQL_PASSWORD: mysql, MYSQL_ALLOW_EMPTY_PASSWORD: 'yes', MYSQL_ROOT_PASSWORD: 'root,' }
nginx:
    image: 'nginx:1.9.0'
    volumes: ['./conf/nginx.conf:/etc/nginx/conf.d/default.conf', './:/var/platform:cached']
    ports: ['80', '443']
    links: [phpfpm]
    environment: { VIRTUAL_HOST: glamanate.platform, PLATFORM_DOCKER: glamanate }
